#ifndef COMPONENT_H
#define COMPONENT_H

/*
  Entities have components. Components carry both data and behavior.
  Component data for entities is stored in fields. Each field is stored
  in a separate array (SoA). There is no concept of a component instance.
  Components must notify the entity management system whenever they add
  a record for an entity, and they also must be able to notified by the
  entity manager whenever an entity is destroyed. Macros have been
  provided for the sake of avoiding boilerplate. All components must
  adher to some standards.

  Notice: The private versions of function is guaranteed to be defined
  by each component separately for custom behavior.

  Every component would have an init function which would be called at
  the start. The init function is generated by the macro, and does the
  initial startup of the component. It also calls the private init
  function which must be defined by the component itself, for custom
  startup behavior. The component must not rely on other components in
  the init function, because the initiation of other components has not
  been guaranteed.

  After the init function, the start function is called which is defined
  by the component. Any startup behavior which relies on other components
  must be done in this function.

  At the end of the game, the system would call the user defined private
  shutdown function, which is used for any custom shutdown behavior.

  Upon the addition and removal of a component from an entity, the
  respective private functions would be called.

  Components must define setters and getter for their public fieds
  (fields that are defined in the header file). But, getters and setters
  for private fields (defined in the translation unit) are optional.

  Removal of components from entities is not done immediately. Removals
  are queued just like entity destructions. Components would do their
  removal first at the end of the frame. After that, the entity manager
  would notify components about the destruction of an entity.
  So, if an entity is both marked for destruction and removal of a
  certain component, the component would be removed first.

  Since the removal mechanism makes component handles unstable, one must
  not retain component handles between frames, and must retrieve them
  every frame.

  Component would have a name##_data struct located in their translation
  unit for storing their fields and the count of entities attached.

  Since fields are stored in dense arrays, it's simply a matter of
  iteration over the dense array, with respect to the variable
  name##_data.count which indicated the count of records.

  For understanding the general structure of component definition, please
  take a look at "gen_component.sh" file.

  Notice: Some fields are reserved and cannot be taken by components.
  (map, rev_map)
  Other than that, the (rem_pending) variable(s) are reserved in the
  name##_data struct by the macros.
*/

#include <gamedef.h>
#include <entity.h>
#include <all_components.h>
#include <dsa.h>

#ifndef NO_EDITOR
#include <editor.h>
#include <inspector.h>
#endif

#include <stddef.h>

#ifndef NO_EDITOR

#define decl_component_inspector(name, public_fields) \
	void name##_inspector_default(Entity ent) { \
		if (editor_tree_push(ED_TREE_NODE, \
				     #name, ED_MINIMIZED)) { \
			name handle = name##_get(ent); \
			public_fields(component_field_inspector); \
			editor_tree_pop(); \
		} \
	}
#else

#define decl_component_inspector(name, public_fields) \
	void name##_inspector_default(Entity ent) { \
		(void)ent; \
	}

#endif /* NO_EDITOR */

#define component_getset_fields(component, type, name) \
	type component##_##name(component); \
	void component##_set_##name(component, type);

#define component_storage_fields(component, type, name) \
	type name[MAX_ENTITY_COUNT];

#define decl_component(name, fields_f) \
	typedef struct { EntityIndex id; } name; \
	\
	void name##_init(void); \
	void name##_shutdown(void); \
	void name##_start(void); \
	name name##_add(Entity); \
	name name##_get(Entity); \
	void name##_rem_entity(Entity); \
	void name##_rem_entity_immediately(Entity); \
	void name##_flush_entities(void); \
	void name##_inspector_default(Entity);	\
	fields_f(component_getset_fields) \
	void name##_inspector_default(Entity)

#define component_copy_last_to_index(component, type, name) \
	component##_data.name[index] = \
		component##_data.name[component##_data.count];


#define component_field_inspector(component, type, name) { \
		editor_layout_row_dynamic(0, 2); \
		editor_label(#name":", ED_ALIGN_RIGHT); \
		editor_label(#type, ED_ALIGN_LEFT); \
		const type *p = &component##_data.name[handle.id]; \
		type##_inspector_widget(ENTITY_INDEX(ent), p, \
					component##_set_##name##_impl); \
	}

#define component_get_set_impl(component, type, name) \
	static inline type component##_##name##_impl(EntityIndex); \
	static inline void component##_set_##name##_impl(EntityIndex, type);\
	type component##_##name(component handle) \
	{ \
		if (handle.id == 0 || \
		    handle.id > (EntityIndex)component##_data.count) \
			return (type){0}; \
		return component##_##name##_impl(handle.id); \
	} \
	\
	void component##_set_##name(component handle, type new_val) \
	{ \
		if (handle.id == 0 || \
		    handle.id > (EntityIndex)component##_data.count) \
			return; \
		component##_set_##name##_impl(handle.id, new_val); \
	}

#define decl_component_storage(name, public_fields, fields_f) \
	struct { \
		int count; \
		struct { Entity *items; size_t count; \
			size_t capacity; } rem_pending; \
		component_storage_fields(name, bool, \
					 pending_remove) \
		\
		component_storage_fields(name, EntityIndex, map) \
		component_storage_fields(name, Entity, rev_map) \
		fields_f(component_storage_fields) \
	} name##_data; \
	\
	static inline void name##_init_private(void); \
	void name##_init(void) { \
		for (int i = 0; i < MAX_ENTITY_COUNT; i++) { \
			name##_data.map[i] = 0; \
			name##_data.rev_map[i] = 0; \
		} \
		name##_data.count = 0; \
		name##_init_private(); \
		name##_data.rem_pending.items = NULL; \
		name##_data.rem_pending.count = 0; \
		name##_data.rem_pending.capacity = 0; \
	} \
	static inline void name##_shutdown_private(void); \
	void name##_shutdown(void) { \
		name##_shutdown_private(); \
		DA_FREE(name##_data.rem_pending.items); \
		name##_data.rem_pending.items = NULL; \
		name##_data.rem_pending.count = 0; \
		name##_data.rem_pending.capacity = 0; \
	} \
	\
	static inline void name##_add_private(Entity, EntityIndex); \
	name name##_add(Entity ent) { \
		EntityIndex ent_index; \
		EntityIndex index; \
		if (!is_entity_valid(ent)) return (name){0}; \
		ent_index = ENTITY_INDEX(ent); \
		index = name##_data.map[ent_index]; \
		if (index != 0) return (name){ index }; \
		index = ++name##_data.count; \
		name##_data.map[ent_index] = index; \
		name##_data.rev_map[index] = ent; \
		name##_data.pending_remove[index] = false; \
		component_added_to_entity(ent, COMPONENT_##name);\
		name##_add_private(ent, index); \
		return (name){index}; \
	} \
	\
	name name##_get(Entity ent) { \
		name handle = {0}; \
		if (!is_entity_valid(ent)) return handle; \
		handle.id = name##_data.map[ENTITY_INDEX(ent)]; \
		return handle; \
	} \
	\
	static inline void name##_rem_private(Entity, EntityIndex); \
	void name##_rem_entity(Entity ent) { \
		EntityIndex index = 0; \
		if (!is_entity_valid(ent)) return; \
		index = name##_data.map[ENTITY_INDEX(ent)]; \
		if (index == 0 || \
		    name##_data.pending_remove[index]) \
			return; \
		\
		da_append(&name##_data.rem_pending, ent);\
		name##_data.pending_remove[index] = true; \
	} \
	\
	static void name##_rem_from_index_immediate( \
		Entity ent, \
		EntityIndex index) { \
		assert(index > 0); \
		assert(index <= (EntityIndex)name##_data.count); \
		assert(name##_data.rev_map[index] == ent); \
		\
		EntityIndex last = name##_data.count; \
		name##_rem_private(ent, index); \
		if (index != last) { \
			fields_f(component_copy_last_to_index); \
			component_copy_last_to_index(\
				name, bool, pending_remove); \
			name##_data.rev_map[index] = \
				name##_data.rev_map[last]; \
			Entity moved = name##_data.rev_map[index]; \
			name##_data.map[ENTITY_INDEX(moved)] = index; \
		} \
		name##_data.map[ENTITY_INDEX(ent)] = 0; \
		name##_data.rev_map[last] = 0; \
		name##_data.count--; \
		component_removed_from_entity( \
			ent, COMPONENT_##name); \
	} \
	\
	void name##_rem_entity_immediately(Entity ent) { \
		if (!is_entity_valid(ent)) return; \
		EntityIndex index = 0; \
		index = name##_data.map[ENTITY_INDEX(ent)]; \
		if (index == 0) return; \
		name##_rem_from_index_immediate(ent, index); \
	} \
	\
	void name##_flush_entities(void) { \
		if (name##_data.rem_pending.count == 0) \
			return; \
		arr_foreach(Entity, ent_p, \
			   &name##_data.rem_pending) { \
			Entity ent = *ent_p; \
			if (!is_entity_valid(ent)) continue; \
			\
			EntityIndex index = name##_data.map[ \
				ENTITY_INDEX(ent)]; \
			if (index == 0 ||				\
			    !name##_data.pending_remove[index]) \
				continue; \
			name##_rem_from_index_immediate(ent, index); \
		} \
		name##_data.rem_pending.count = 0; \
	} \
	\
	public_fields(component_get_set_impl) \
	\
	decl_component_inspector(name, public_fields)

#endif /* COMPONENT_H */
