#ifndef GAMEDEF_H
#define GAMEDEF_H

#define ASPECT_RATIO (1920.0f/1080.0f)
#define GAME_VIEW_HEIGHT 10.0f
#define GAME_VIEW_WIDTH GAME_VIEW_HEIGHT*ASPECT_RATIO
#define MAX_ENTITY_COUNT 256

#endif /* GAMEDEF_H */
